// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4G8VaE5PvDjfgEv1I58y4CZRA-xjoC0U',
    appId: '1:750232453198:web:091d77727a8c706044831f',
    messagingSenderId: '750232453198',
    projectId: 'testing-73c98',
    authDomain: 'testing-73c98.firebaseapp.com',
    storageBucket: 'testing-73c98.appspot.com',
    measurementId: 'G-X1HT99RLHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwlHTcA5VJq7Ac49Z04FDNGJ2K2Qvu2xM',
    appId: '1:750232453198:android:08506ce57335b77944831f',
    messagingSenderId: '750232453198',
    projectId: 'testing-73c98',
    storageBucket: 'testing-73c98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBECV7MeUVZjzWoqKXNaaWy5TYmcc8EUxE',
    appId: '1:750232453198:ios:49e5e0c5594bd08644831f',
    messagingSenderId: '750232453198',
    projectId: 'testing-73c98',
    storageBucket: 'testing-73c98.appspot.com',
    iosClientId: '750232453198-5dtu2p05up8hbh92f2pggv50d0vbttii.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBECV7MeUVZjzWoqKXNaaWy5TYmcc8EUxE',
    appId: '1:750232453198:ios:49e5e0c5594bd08644831f',
    messagingSenderId: '750232453198',
    projectId: 'testing-73c98',
    storageBucket: 'testing-73c98.appspot.com',
    iosClientId: '750232453198-5dtu2p05up8hbh92f2pggv50d0vbttii.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoshare',
  );
}
